### ISSUE TITLE
우리 스터디 제목으로 뭐가 좋을까요? :rocket: 

### ISSUE THREAD

**Issue by wonseok2877** [wonseok2877/CS-study#31]
여기에 뜰 제목이예요.
![image](https://user-images.githubusercontent.com/72124326/216776133-da3e2094-dcab-437f-9b7b-34e49c54f6d2.png)

1. 👨‍💻 Computer Science nerd🤪들의 지식 정리 공간

2. 👨‍💻 면접대비..라기엔 너무 꼼꼼한 CS학도들🤪의 지식 정리 공간

3. 👨‍💻 CS 면접 solution[ 52 + α ]

우리의 정체성을 나타내는 한 줄이기도 해서 뭔가 심사숙고하게 되더랍니다?

30분간 고민해봤지만 확 삘 받는게 없는 상태..뭐가 좋을까요?

**Comment by WooYoungDoo** [comment]
흠 어렵네요

**Comment by hs1430** [comment]
3번이 괜찮아보이네요
